[package]
name = "stack"
authors = ["rakete"]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
nom = "7.1.3"

[profile.release]
strip = true
lto = "fat"
